version: '1.0'
name: docs-build
displayName: Docs Build
triggers:
  trigger: auto
  push:
    branches:
      include:
        - main
  pr:
    branches:
      include:
        - main
stages:
  - name: build
    displayName: Build VitePress
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Node.js Build
        nodeVersion: 22.22.0
        commands:
          - node -v
          - npm -v
          - npm ci
          - npm run docs:build
        artifacts:
          - name: DOCS_DIST
            path:
              - ./docs/.vitepress/dist
        caches:
          - ~/.npm
        notify: []
        strategy:
          retry: '0'
