version: '1.0'
name: docs-build
displayName: 文档构建
triggers:
  trigger: auto
  push:
    branches:
      include:
        - main
stages:
  - name: build
    displayName: 构建文档
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs构建
        nodeVersion: 22.22.0
        commands:
          - node -v
          - npm -v
          - npm config set registry https://registry.npmmirror.com
          - npm ci
          - rm -rf docs/.vitepress/dist
          - npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vitepress/dist
        caches:
          - ~/.npm
        notify: []
        strategy:
          retry: '0'
